package com.AiTongue.Vo;

import lombok.Data;

import java.util.List;

/**
 * @Author: 翰林猿
 * @Description: 返回给前端展示舌诊报告需要的值
 **/

@Data
public class userTongueVo {
    private int age;
    private String aijiu;
    private String bagang;
    private String bagangDesc;
    private int botai;
    private String botaiDesc;
    private String botaiMean;
    private int chagndao;
    private String chagndaoDesc;
    private String chagndaoMean;
    private int chihen;
    private String chihenDesc;
    private String chihenMean;
    private String createTime;
    private int dianci;
    private String dianciDesc;
    private String dianciMean;
    private String feel;
    private int fei;
    private String feiDesc;
    private String feiMean;
    private String food;
    private boolean frontCamera;
    private int gandan;
    private String gandanDesc;
    private String gandanMean;
    private List<String> goods;
    private int id;
    private int isYuejin;
    private int liewen;
    private String liewenDesc;
    private String liewenMean;
    private String life;
    private int male;
    private String medical;
    private String name;
    private int nao;
    private String naoDesc;
    private String naoMean;
    private int nuanchao;
    private String nuanchaoDesc;
    private String nuanchaoMean;
    private String pdfUrl;
    private int pifu;
    private String pifuDesc;
    private String pifuMean;
    private int piwei;
    private String piweiDesc;
    private String piweiMean;
    private int qianliexian;
    private String qianliexianDesc;
    private String qianliexianMean;
    private int qiji;
    private String qijiDesc;
    private String qijiMean;
    private String qixiaoDesc;
    private String recomand;
    private String roiImage;
    private int ruxian;
    private String ruxianDesc;
    private String ruxianMean;
    private int score;
    private String scoreDesc;
    private List<String> sheSeRadarData;
    private List<String> sheSeTableXData;
    private List<String> sheSeTableYData;
    private float shemianConfidence;
    private String shemianDesc;
    private String shemianName;
    private int shen;
    private String shenDesc;
    private String shenMean;
    private float shexinConfidence;
    private String shexinDesc;
    private String shexinName;
    private String sport;
    private String symptom;
    private String symptomDesc;
    private List<String> taiSeRadarData;
    private List<String> taiSeTableXData;
    private List<String> taiSeTableYData;
    private float taiseConfidence;
    private String taiseDesc;
    private String taiseName;
    private float taizhiConfidence;
    private String taizhiDesc;
    private String taizhiName;
    private List<String> tizhiRadarData;
    private List<String> tizhiTableXData;
    private List<String> tizhiTableYData;
    private String tonguePicAddr;
    private float typeConfidence;
    private int typeId;
    private String typeName;
    private String uid;
    private String uploadPath;
    private int xinzang;
    private String xinzangDesc;
    private String xinzangMean;
    private int yuban;
    private String yubanDesc;
    private String yubanMean;
    private int yudian;
    private String yudianDesc;
    private String yudianMean;
    private String zhengxing;
    private String zhengxingDesc;
    private int zigon;
    private String zigonDesc;
    private String zigonMean;
}
